CREATE TABLE USUARIO(
  ID_USUARIO NUMERIC(4) NOT NULL PRIMARY KEY,
  USUARIO VARCHAR2(20) NOT NULL UNIQUE,
  CLAVE VARCHAR2(80) NOT NULL,
  NOMBRE VARCHAR2(120) NOT NULL UNIQUE,
  
  ESTADO CHAR(1)DEFAULT '1' NOT NULL ,
  
  AUD_TIPO CHAR(1) NULL,
  AUD_IDUSUARIO NUMERIC(10,0) NULL,
  AUD_SESION VARCHAR(60) NULL,
  AUD_FECHA DATE NULL,
  AUD_IP VARCHAR(20) NULL
);

CREATE SEQUENCE SEQ_USUARIO;

INSERT INTO USUARIO(ID_USUARIO,USUARIO,CLAVE,NOMBRE,ESTADO,AUD_TIPO,AUD_IDUSUARIO,AUD_SESION,AUD_FECHA,AUD_IP)
VALUES(SEQ_USUARIO.NEXTVAL,'ADMIN','14F2WLU7Jmg=','ADMINISTRADOR','1','I',1,'S1','17-03-2018','192.168.1.26');
INSERT INTO USUARIO(ID_USUARIO,USUARIO,CLAVE,NOMBRE,ESTADO,AUD_TIPO,AUD_IDUSUARIO,AUD_SESION,AUD_FECHA,AUD_IP)
VALUES(SEQ_USUARIO.NEXTVAL,'DEMO','xdlOnb5Nv0M=','DEMOSTRACIÓN','1','I',1,'S2','17-03-2018','192.168.1.26');
INSERT INTO USUARIO(ID_USUARIO,USUARIO,CLAVE,NOMBRE,ESTADO,AUD_TIPO,AUD_IDUSUARIO,AUD_SESION,AUD_FECHA,AUD_IP)
VALUES(SEQ_USUARIO.NEXTVAL,'INV','p7/kTqq1PKE=','INVITADO','1','I',1,'S2','17-03-2018','192.168.1.26');

COMMIT;
SELECT * FROM USUARIO;



